# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sitUpsTest.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QObject,pyqtSignal
import utils.readCardUtils
# import utils.pyMysqlUtils
import utils.mysqlUtil
import uuid
import time
import serial
import _thread
# from threading import Thread


class Ui_Form(QObject):

    nowPerson=0
    allPerson=0
    dataFlag = False
    readCardFlag = False
    showMsgSignal = pyqtSignal(str)
    lastCardId = ''
    stat = utils.mysqlUtil.MysqlUtil()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 140, 1013, 502))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bh_21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_21.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_21.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_21.setReadOnly(True)
        self.bh_21.setObjectName("bh_21")
        self.gridLayout.addWidget(self.bh_21, 1, 9, 1, 1)
        self.cj_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_24.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_24.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_24.setFont(font)
        self.cj_24.setText("")
        self.cj_24.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_24.setObjectName("cj_24")
        self.gridLayout.addWidget(self.cj_24, 4, 11, 1, 1)
        self.sb_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_21.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_21.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_21.setFont(font)
        self.sb_21.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_21.setObjectName("sb_21")
        self.gridLayout.addWidget(self.sb_21, 1, 8, 1, 1)
        self.cj_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_22.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_22.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_22.setFont(font)
        self.cj_22.setText("")
        self.cj_22.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_22.setObjectName("cj_22")
        self.gridLayout.addWidget(self.cj_22, 2, 11, 1, 1)
        self.sb_title_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_title_2.setMinimumSize(QtCore.QSize(60, 40))
        self.sb_title_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_title_2.setFont(font)
        self.sb_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_title_2.setObjectName("sb_title_2")
        self.gridLayout.addWidget(self.sb_title_2, 0, 4, 1, 1)
        self.mc_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_21.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_21.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_21.setFont(font)
        self.mc_21.setText("")
        self.mc_21.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_21.setObjectName("mc_21")
        self.gridLayout.addWidget(self.mc_21, 1, 10, 1, 1)
        self.cj_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_21.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_21.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_21.setFont(font)
        self.cj_21.setText("")
        self.cj_21.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_21.setObjectName("cj_21")
        self.gridLayout.addWidget(self.cj_21, 1, 11, 1, 1)
        self.mc_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_29.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_29.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_29.setFont(font)
        self.mc_29.setText("")
        self.mc_29.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_29.setObjectName("mc_29")
        self.gridLayout.addWidget(self.mc_29, 9, 10, 1, 1)
        self.mc_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_18.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_18.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_18.setFont(font)
        self.mc_18.setText("")
        self.mc_18.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_18.setObjectName("mc_18")
        self.gridLayout.addWidget(self.mc_18, 8, 6, 1, 1)
        self.mc_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_19.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_19.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_19.setFont(font)
        self.mc_19.setText("")
        self.mc_19.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_19.setObjectName("mc_19")
        self.gridLayout.addWidget(self.mc_19, 9, 6, 1, 1)
        self.cj_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_16.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_16.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_16.setFont(font)
        self.cj_16.setText("")
        self.cj_16.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_16.setObjectName("cj_16")
        self.gridLayout.addWidget(self.cj_16, 6, 7, 1, 1)
        self.cj_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_19.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_19.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_19.setFont(font)
        self.cj_19.setText("")
        self.cj_19.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_19.setObjectName("cj_19")
        self.gridLayout.addWidget(self.cj_19, 9, 7, 1, 1)
        self.sb_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_23.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_23.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_23.setFont(font)
        self.sb_23.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_23.setObjectName("sb_23")
        self.gridLayout.addWidget(self.sb_23, 3, 8, 1, 1)
        self.cj_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_17.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_17.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_17.setFont(font)
        self.cj_17.setText("")
        self.cj_17.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_17.setObjectName("cj_17")
        self.gridLayout.addWidget(self.cj_17, 7, 7, 1, 1)
        self.cj_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_11.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_11.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_11.setFont(font)
        self.cj_11.setText("")
        self.cj_11.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_11.setObjectName("cj_11")
        self.gridLayout.addWidget(self.cj_11, 1, 7, 1, 1)
        self.mc_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_20.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_20.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_20.setFont(font)
        self.mc_20.setText("")
        self.mc_20.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_20.setObjectName("mc_20")
        self.gridLayout.addWidget(self.mc_20, 10, 6, 1, 1)
        self.cj_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_15.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_15.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_15.setFont(font)
        self.cj_15.setText("")
        self.cj_15.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_15.setObjectName("cj_15")
        self.gridLayout.addWidget(self.cj_15, 5, 7, 1, 1)
        self.cj_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_13.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_13.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_13.setFont(font)
        self.cj_13.setText("")
        self.cj_13.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_13.setObjectName("cj_13")
        self.gridLayout.addWidget(self.cj_13, 3, 7, 1, 1)
        self.mc_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_16.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_16.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_16.setFont(font)
        self.mc_16.setText("")
        self.mc_16.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_16.setObjectName("mc_16")
        self.gridLayout.addWidget(self.mc_16, 6, 6, 1, 1)
        self.mc_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_15.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_15.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_15.setFont(font)
        self.mc_15.setText("")
        self.mc_15.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_15.setObjectName("mc_15")
        self.gridLayout.addWidget(self.mc_15, 5, 6, 1, 1)
        self.mc_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_11.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_11.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_11.setFont(font)
        self.mc_11.setText("")
        self.mc_11.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_11.setObjectName("mc_11")
        self.gridLayout.addWidget(self.mc_11, 1, 6, 1, 1)
        self.mc_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_14.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_14.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_14.setFont(font)
        self.mc_14.setText("")
        self.mc_14.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_14.setObjectName("mc_14")
        self.gridLayout.addWidget(self.mc_14, 4, 6, 1, 1)
        self.mc_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_12.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_12.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_12.setFont(font)
        self.mc_12.setText("")
        self.mc_12.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_12.setObjectName("mc_12")
        self.gridLayout.addWidget(self.mc_12, 2, 6, 1, 1)
        self.cj_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_14.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_14.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_14.setFont(font)
        self.cj_14.setText("")
        self.cj_14.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_14.setObjectName("cj_14")
        self.gridLayout.addWidget(self.cj_14, 4, 7, 1, 1)
        self.bh_20 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_20.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_20.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_20.setReadOnly(True)
        self.bh_20.setObjectName("bh_20")
        self.gridLayout.addWidget(self.bh_20, 10, 5, 1, 1)
        self.mc_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_13.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_13.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_13.setFont(font)
        self.mc_13.setText("")
        self.mc_13.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_13.setObjectName("mc_13")
        self.gridLayout.addWidget(self.mc_13, 3, 6, 1, 1)
        self.bh_19 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_19.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_19.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_19.setReadOnly(True)
        self.bh_19.setObjectName("bh_19")
        self.gridLayout.addWidget(self.bh_19, 9, 5, 1, 1)
        self.bh_18 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_18.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_18.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_18.setReadOnly(True)
        self.bh_18.setObjectName("bh_18")
        self.gridLayout.addWidget(self.bh_18, 8, 5, 1, 1)
        self.bh_17 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_17.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_17.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_17.setReadOnly(True)
        self.bh_17.setObjectName("bh_17")
        self.gridLayout.addWidget(self.bh_17, 7, 5, 1, 1)
        self.bh_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_16.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_16.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_16.setReadOnly(True)
        self.bh_16.setObjectName("bh_16")
        self.gridLayout.addWidget(self.bh_16, 6, 5, 1, 1)
        self.bh_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_15.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_15.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_15.setReadOnly(True)
        self.bh_15.setObjectName("bh_15")
        self.gridLayout.addWidget(self.bh_15, 5, 5, 1, 1)
        self.bh_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_14.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_14.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_14.setReadOnly(True)
        self.bh_14.setObjectName("bh_14")
        self.gridLayout.addWidget(self.bh_14, 4, 5, 1, 1)
        self.bh_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_13.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_13.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_13.setReadOnly(True)
        self.bh_13.setObjectName("bh_13")
        self.gridLayout.addWidget(self.bh_13, 3, 5, 1, 1)
        self.bh_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_12.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_12.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_12.setReadOnly(True)
        self.bh_12.setObjectName("bh_12")
        self.gridLayout.addWidget(self.bh_12, 2, 5, 1, 1)
        self.cj_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_10.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_10.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_10.setFont(font)
        self.cj_10.setText("")
        self.cj_10.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_10.setObjectName("cj_10")
        self.gridLayout.addWidget(self.cj_10, 10, 3, 1, 1)
        self.cj_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_9.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_9.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_9.setFont(font)
        self.cj_9.setText("")
        self.cj_9.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_9.setObjectName("cj_9")
        self.gridLayout.addWidget(self.cj_9, 9, 3, 1, 1)
        self.cj_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_8.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_8.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_8.setFont(font)
        self.cj_8.setText("")
        self.cj_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_8.setObjectName("cj_8")
        self.gridLayout.addWidget(self.cj_8, 8, 3, 1, 1)
        self.cj_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_7.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_7.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_7.setFont(font)
        self.cj_7.setText("")
        self.cj_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_7.setObjectName("cj_7")
        self.gridLayout.addWidget(self.cj_7, 7, 3, 1, 1)
        self.mc_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_1.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_1.setFont(font)
        self.mc_1.setText("")
        self.mc_1.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_1.setObjectName("mc_1")
        self.gridLayout.addWidget(self.mc_1, 1, 2, 1, 1)
        self.mc_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_17.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_17.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_17.setFont(font)
        self.mc_17.setText("")
        self.mc_17.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_17.setObjectName("mc_17")
        self.gridLayout.addWidget(self.mc_17, 7, 6, 1, 1)
        self.cj_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_6.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_6.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_6.setFont(font)
        self.cj_6.setText("")
        self.cj_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_6.setObjectName("cj_6")
        self.gridLayout.addWidget(self.cj_6, 6, 3, 1, 1)
        self.cj_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_25.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_25.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_25.setFont(font)
        self.cj_25.setText("")
        self.cj_25.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_25.setObjectName("cj_25")
        self.gridLayout.addWidget(self.cj_25, 5, 11, 1, 1)
        self.bh_22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_22.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_22.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_22.setReadOnly(True)
        self.bh_22.setObjectName("bh_22")
        self.gridLayout.addWidget(self.bh_22, 2, 9, 1, 1)
        self.cj_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_12.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_12.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_12.setFont(font)
        self.cj_12.setText("")
        self.cj_12.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_12.setObjectName("cj_12")
        self.gridLayout.addWidget(self.cj_12, 2, 7, 1, 1)
        self.cj_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_20.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_20.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_20.setFont(font)
        self.cj_20.setText("")
        self.cj_20.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_20.setObjectName("cj_20")
        self.gridLayout.addWidget(self.cj_20, 10, 7, 1, 1)
        self.cj_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_18.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_18.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_18.setFont(font)
        self.cj_18.setText("")
        self.cj_18.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_18.setObjectName("cj_18")
        self.gridLayout.addWidget(self.cj_18, 8, 7, 1, 1)
        self.cj_title_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_title_3.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_title_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_title_3.setFont(font)
        self.cj_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_title_3.setObjectName("cj_title_3")
        self.gridLayout.addWidget(self.cj_title_3, 0, 11, 1, 1)
        self.cj_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_29.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_29.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_29.setFont(font)
        self.cj_29.setText("")
        self.cj_29.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_29.setObjectName("cj_29")
        self.gridLayout.addWidget(self.cj_29, 9, 11, 1, 1)
        self.cj_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_26.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_26.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_26.setFont(font)
        self.cj_26.setText("")
        self.cj_26.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_26.setObjectName("cj_26")
        self.gridLayout.addWidget(self.cj_26, 6, 11, 1, 1)
        self.cj_title_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_title_2.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_title_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_title_2.setFont(font)
        self.cj_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_title_2.setObjectName("cj_title_2")
        self.gridLayout.addWidget(self.cj_title_2, 0, 7, 1, 1)
        self.cj_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_30.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_30.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_30.setFont(font)
        self.cj_30.setText("")
        self.cj_30.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_30.setObjectName("cj_30")
        self.gridLayout.addWidget(self.cj_30, 10, 11, 1, 1)
        self.cj_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_27.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_27.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_27.setFont(font)
        self.cj_27.setText("")
        self.cj_27.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_27.setObjectName("cj_27")
        self.gridLayout.addWidget(self.cj_27, 7, 11, 1, 1)
        self.sb_title_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_title_3.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_title_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_title_3.setFont(font)
        self.sb_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_title_3.setObjectName("sb_title_3")
        self.gridLayout.addWidget(self.sb_title_3, 0, 8, 1, 1)
        self.cj_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_28.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_28.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_28.setFont(font)
        self.cj_28.setText("")
        self.cj_28.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_28.setObjectName("cj_28")
        self.gridLayout.addWidget(self.cj_28, 8, 11, 1, 1)
        self.mc_title_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_title_3.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_title_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_title_3.setFont(font)
        self.mc_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_title_3.setObjectName("mc_title_3")
        self.gridLayout.addWidget(self.mc_title_3, 0, 10, 1, 1)
        self.bh_title_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bh_title_3.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_title_3.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.bh_title_3.setFont(font)
        self.bh_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.bh_title_3.setObjectName("bh_title_3")
        self.gridLayout.addWidget(self.bh_title_3, 0, 9, 1, 1)
        self.sb_title_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_title_1.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_title_1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_title_1.setFont(font)
        self.sb_title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_title_1.setObjectName("sb_title_1")
        self.gridLayout.addWidget(self.sb_title_1, 0, 0, 1, 1)
        self.bh_title_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bh_title_1.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_title_1.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.bh_title_1.setFont(font)
        self.bh_title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.bh_title_1.setObjectName("bh_title_1")
        self.gridLayout.addWidget(self.bh_title_1, 0, 1, 1, 1)
        self.cj_title_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_title_1.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_title_1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_title_1.setFont(font)
        self.cj_title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_title_1.setObjectName("cj_title_1")
        self.gridLayout.addWidget(self.cj_title_1, 0, 3, 1, 1)
        self.mc_title_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_title_1.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_title_1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_title_1.setFont(font)
        self.mc_title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_title_1.setObjectName("mc_title_1")
        self.gridLayout.addWidget(self.mc_title_1, 0, 2, 1, 1)
        self.mc_title_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_title_2.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_title_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_title_2.setFont(font)
        self.mc_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_title_2.setObjectName("mc_title_2")
        self.gridLayout.addWidget(self.mc_title_2, 0, 6, 1, 1)
        self.sb_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_4.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_4.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_4.setFont(font)
        self.sb_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_4.setObjectName("sb_4")
        self.gridLayout.addWidget(self.sb_4, 4, 0, 1, 1)
        self.bh_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_2.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_2.setReadOnly(True)
        self.bh_2.setObjectName("bh_2")
        self.gridLayout.addWidget(self.bh_2, 2, 1, 1, 1)
        self.sb_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_1.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_1.setFont(font)
        self.sb_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_1.setObjectName("sb_1")
        self.gridLayout.addWidget(self.sb_1, 1, 0, 1, 1)
        self.bh_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_9.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_9.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_9.setReadOnly(True)
        self.bh_9.setObjectName("bh_9")
        self.gridLayout.addWidget(self.bh_9, 9, 1, 1, 1)
        self.sb_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_2.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_2.setFont(font)
        self.sb_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_2.setObjectName("sb_2")
        self.gridLayout.addWidget(self.sb_2, 2, 0, 1, 1)
        self.sb_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_3.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_3.setFont(font)
        self.sb_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_3.setObjectName("sb_3")
        self.gridLayout.addWidget(self.sb_3, 3, 0, 1, 1)
        self.sb_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_5.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_5.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_5.setFont(font)
        self.sb_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_5.setObjectName("sb_5")
        self.gridLayout.addWidget(self.sb_5, 5, 0, 1, 1)
        self.sb_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_6.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_6.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_6.setFont(font)
        self.sb_6.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_6.setObjectName("sb_6")
        self.gridLayout.addWidget(self.sb_6, 6, 0, 1, 1)
        self.sb_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_7.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_7.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_7.setFont(font)
        self.sb_7.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_7.setObjectName("sb_7")
        self.gridLayout.addWidget(self.sb_7, 7, 0, 1, 1)
        self.bh_23 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_23.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_23.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_23.setReadOnly(True)
        self.bh_23.setObjectName("bh_23")
        self.gridLayout.addWidget(self.bh_23, 3, 9, 1, 1)
        self.mc_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_23.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_23.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_23.setFont(font)
        self.mc_23.setText("")
        self.mc_23.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_23.setObjectName("mc_23")
        self.gridLayout.addWidget(self.mc_23, 3, 10, 1, 1)
        self.mc_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_26.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_26.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_26.setFont(font)
        self.mc_26.setText("")
        self.mc_26.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_26.setObjectName("mc_26")
        self.gridLayout.addWidget(self.mc_26, 6, 10, 1, 1)
        self.mc_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_22.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_22.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_22.setFont(font)
        self.mc_22.setText("")
        self.mc_22.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_22.setObjectName("mc_22")
        self.gridLayout.addWidget(self.mc_22, 2, 10, 1, 1)
        self.bh_26 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_26.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_26.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_26.setReadOnly(True)
        self.bh_26.setObjectName("bh_26")
        self.gridLayout.addWidget(self.bh_26, 6, 9, 1, 1)
        self.bh_25 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_25.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_25.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_25.setReadOnly(True)
        self.bh_25.setObjectName("bh_25")
        self.gridLayout.addWidget(self.bh_25, 5, 9, 1, 1)
        self.bh_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_6.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_6.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_6.setReadOnly(True)
        self.bh_6.setObjectName("bh_6")
        self.gridLayout.addWidget(self.bh_6, 6, 1, 1, 1)
        self.cj_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_1.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_1.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_1.setFont(font)
        self.cj_1.setText("")
        self.cj_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_1.setObjectName("cj_1")
        self.gridLayout.addWidget(self.cj_1, 1, 3, 1, 1)
        self.bh_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_5.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_5.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_5.setReadOnly(True)
        self.bh_5.setObjectName("bh_5")
        self.gridLayout.addWidget(self.bh_5, 5, 1, 1, 1)
        self.mc_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_30.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_30.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_30.setFont(font)
        self.mc_30.setText("")
        self.mc_30.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_30.setObjectName("mc_30")
        self.gridLayout.addWidget(self.mc_30, 10, 10, 1, 1)
        self.bh_30 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_30.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_30.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_30.setReadOnly(True)
        self.bh_30.setObjectName("bh_30")
        self.gridLayout.addWidget(self.bh_30, 10, 9, 1, 1)
        self.mc_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_27.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_27.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_27.setFont(font)
        self.mc_27.setText("")
        self.mc_27.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_27.setObjectName("mc_27")
        self.gridLayout.addWidget(self.mc_27, 7, 10, 1, 1)
        self.mc_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_25.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_25.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_25.setFont(font)
        self.mc_25.setText("")
        self.mc_25.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_25.setObjectName("mc_25")
        self.gridLayout.addWidget(self.mc_25, 5, 10, 1, 1)
        self.cj_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_23.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_23.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_23.setFont(font)
        self.cj_23.setText("")
        self.cj_23.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_23.setObjectName("cj_23")
        self.gridLayout.addWidget(self.cj_23, 3, 11, 1, 1)
        self.bh_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_4.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_4.setReadOnly(True)
        self.bh_4.setObjectName("bh_4")
        self.gridLayout.addWidget(self.bh_4, 4, 1, 1, 1)
        self.mc_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_7.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_7.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_7.setFont(font)
        self.mc_7.setText("")
        self.mc_7.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_7.setObjectName("mc_7")
        self.gridLayout.addWidget(self.mc_7, 7, 2, 1, 1)
        self.sb_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_30.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_30.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_30.setFont(font)
        self.sb_30.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_30.setObjectName("sb_30")
        self.gridLayout.addWidget(self.sb_30, 10, 8, 1, 1)
        self.sb_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_24.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_24.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_24.setFont(font)
        self.sb_24.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_24.setObjectName("sb_24")
        self.gridLayout.addWidget(self.sb_24, 4, 8, 1, 1)
        self.cj_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_4.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_4.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_4.setFont(font)
        self.cj_4.setText("")
        self.cj_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_4.setObjectName("cj_4")
        self.gridLayout.addWidget(self.cj_4, 4, 3, 1, 1)
        self.bh_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_8.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_8.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_8.setReadOnly(True)
        self.bh_8.setObjectName("bh_8")
        self.gridLayout.addWidget(self.bh_8, 8, 1, 1, 1)
        self.sb_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_14.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_14.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_14.setFont(font)
        self.sb_14.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_14.setObjectName("sb_14")
        self.gridLayout.addWidget(self.sb_14, 4, 4, 1, 1)
        self.bh_28 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_28.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_28.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_28.setReadOnly(True)
        self.bh_28.setObjectName("bh_28")
        self.gridLayout.addWidget(self.bh_28, 8, 9, 1, 1)
        self.mc_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_9.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_9.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_9.setFont(font)
        self.mc_9.setText("")
        self.mc_9.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_9.setObjectName("mc_9")
        self.gridLayout.addWidget(self.mc_9, 9, 2, 1, 1)
        self.cj_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_5.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_5.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_5.setFont(font)
        self.cj_5.setText("")
        self.cj_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_5.setObjectName("cj_5")
        self.gridLayout.addWidget(self.cj_5, 5, 3, 1, 1)
        self.sb_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_10.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_10.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_10.setFont(font)
        self.sb_10.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_10.setObjectName("sb_10")
        self.gridLayout.addWidget(self.sb_10, 10, 0, 1, 1)
        self.bh_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_1.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_1.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_1.setReadOnly(True)
        self.bh_1.setObjectName("bh_1")
        self.gridLayout.addWidget(self.bh_1, 1, 1, 1, 1)
        self.sb_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_27.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_27.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_27.setFont(font)
        self.sb_27.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_27.setObjectName("sb_27")
        self.gridLayout.addWidget(self.sb_27, 7, 8, 1, 1)
        self.sb_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_9.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_9.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_9.setFont(font)
        self.sb_9.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_9.setObjectName("sb_9")
        self.gridLayout.addWidget(self.sb_9, 9, 0, 1, 1)
        self.mc_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_4.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_4.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_4.setFont(font)
        self.mc_4.setText("")
        self.mc_4.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_4.setObjectName("mc_4")
        self.gridLayout.addWidget(self.mc_4, 4, 2, 1, 1)
        self.sb_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_8.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_8.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_8.setFont(font)
        self.sb_8.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_8.setObjectName("sb_8")
        self.gridLayout.addWidget(self.sb_8, 8, 0, 1, 1)
        self.mc_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_28.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_28.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_28.setFont(font)
        self.mc_28.setText("")
        self.mc_28.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_28.setObjectName("mc_28")
        self.gridLayout.addWidget(self.mc_28, 8, 10, 1, 1)
        self.sb_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_29.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_29.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_29.setFont(font)
        self.sb_29.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_29.setObjectName("sb_29")
        self.gridLayout.addWidget(self.sb_29, 9, 8, 1, 1)
        self.bh_title_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.bh_title_2.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_title_2.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.bh_title_2.setFont(font)
        self.bh_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.bh_title_2.setObjectName("bh_title_2")
        self.gridLayout.addWidget(self.bh_title_2, 0, 5, 1, 1)
        self.bh_29 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_29.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_29.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_29.setReadOnly(True)
        self.bh_29.setObjectName("bh_29")
        self.gridLayout.addWidget(self.bh_29, 9, 9, 1, 1)
        self.bh_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_7.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_7.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_7.setReadOnly(True)
        self.bh_7.setObjectName("bh_7")
        self.gridLayout.addWidget(self.bh_7, 7, 1, 1, 1)
        self.sb_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_19.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_19.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_19.setFont(font)
        self.sb_19.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_19.setObjectName("sb_19")
        self.gridLayout.addWidget(self.sb_19, 9, 4, 1, 1)
        self.cj_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_3.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_3.setFont(font)
        self.cj_3.setText("")
        self.cj_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_3.setObjectName("cj_3")
        self.gridLayout.addWidget(self.cj_3, 3, 3, 1, 1)
        self.bh_24 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_24.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_24.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_24.setReadOnly(True)
        self.bh_24.setObjectName("bh_24")
        self.gridLayout.addWidget(self.bh_24, 4, 9, 1, 1)
        self.mc_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_5.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_5.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_5.setFont(font)
        self.mc_5.setText("")
        self.mc_5.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_5.setObjectName("mc_5")
        self.gridLayout.addWidget(self.mc_5, 5, 2, 1, 1)
        self.bh_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_3.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_3.setReadOnly(True)
        self.bh_3.setObjectName("bh_3")
        self.gridLayout.addWidget(self.bh_3, 3, 1, 1, 1)
        self.bh_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_10.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_10.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_10.setReadOnly(True)
        self.bh_10.setObjectName("bh_10")
        self.gridLayout.addWidget(self.bh_10, 10, 1, 1, 1)
        self.sb_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_28.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_28.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_28.setFont(font)
        self.sb_28.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_28.setObjectName("sb_28")
        self.gridLayout.addWidget(self.sb_28, 8, 8, 1, 1)
        self.sb_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_22.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_22.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_22.setFont(font)
        self.sb_22.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_22.setObjectName("sb_22")
        self.gridLayout.addWidget(self.sb_22, 2, 8, 1, 1)
        self.sb_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_25.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_25.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_25.setFont(font)
        self.sb_25.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_25.setObjectName("sb_25")
        self.gridLayout.addWidget(self.sb_25, 5, 8, 1, 1)
        self.sb_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_11.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_11.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_11.setFont(font)
        self.sb_11.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_11.setObjectName("sb_11")
        self.gridLayout.addWidget(self.sb_11, 1, 4, 1, 1)
        self.sb_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_17.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_17.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_17.setFont(font)
        self.sb_17.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_17.setObjectName("sb_17")
        self.gridLayout.addWidget(self.sb_17, 7, 4, 1, 1)
        self.sb_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_13.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_13.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_13.setFont(font)
        self.sb_13.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_13.setObjectName("sb_13")
        self.gridLayout.addWidget(self.sb_13, 3, 4, 1, 1)
        self.sb_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_16.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_16.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_16.setFont(font)
        self.sb_16.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_16.setObjectName("sb_16")
        self.gridLayout.addWidget(self.sb_16, 6, 4, 1, 1)
        self.mc_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_6.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_6.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_6.setFont(font)
        self.mc_6.setText("")
        self.mc_6.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_6.setObjectName("mc_6")
        self.gridLayout.addWidget(self.mc_6, 6, 2, 1, 1)
        self.mc_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_10.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_10.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_10.setFont(font)
        self.mc_10.setText("")
        self.mc_10.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_10.setObjectName("mc_10")
        self.gridLayout.addWidget(self.mc_10, 10, 2, 1, 1)
        self.sb_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_26.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_26.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_26.setFont(font)
        self.sb_26.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_26.setObjectName("sb_26")
        self.gridLayout.addWidget(self.sb_26, 6, 8, 1, 1)
        self.mc_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_8.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_8.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_8.setFont(font)
        self.mc_8.setText("")
        self.mc_8.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_8.setObjectName("mc_8")
        self.gridLayout.addWidget(self.mc_8, 8, 2, 1, 1)
        self.sb_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_12.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_12.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_12.setFont(font)
        self.sb_12.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_12.setObjectName("sb_12")
        self.gridLayout.addWidget(self.sb_12, 2, 4, 1, 1)
        self.sb_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_20.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_20.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_20.setFont(font)
        self.sb_20.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_20.setObjectName("sb_20")
        self.gridLayout.addWidget(self.sb_20, 10, 4, 1, 1)
        self.sb_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_18.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_18.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_18.setFont(font)
        self.sb_18.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_18.setObjectName("sb_18")
        self.gridLayout.addWidget(self.sb_18, 8, 4, 1, 1)
        self.sb_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sb_15.setMinimumSize(QtCore.QSize(65, 40))
        self.sb_15.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sb_15.setFont(font)
        self.sb_15.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_15.setObjectName("sb_15")
        self.gridLayout.addWidget(self.sb_15, 5, 4, 1, 1)
        self.mc_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_3.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_3.setFont(font)
        self.mc_3.setText("")
        self.mc_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_3.setObjectName("mc_3")
        self.gridLayout.addWidget(self.mc_3, 3, 2, 1, 1)
        self.mc_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_2.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_2.setFont(font)
        self.mc_2.setText("")
        self.mc_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_2.setObjectName("mc_2")
        self.gridLayout.addWidget(self.mc_2, 2, 2, 1, 1)
        self.cj_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cj_2.setMinimumSize(QtCore.QSize(60, 40))
        self.cj_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cj_2.setFont(font)
        self.cj_2.setText("")
        self.cj_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cj_2.setObjectName("cj_2")
        self.gridLayout.addWidget(self.cj_2, 2, 3, 1, 1)
        self.mc_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mc_24.setMinimumSize(QtCore.QSize(60, 40))
        self.mc_24.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mc_24.setFont(font)
        self.mc_24.setText("")
        self.mc_24.setAlignment(QtCore.Qt.AlignCenter)
        self.mc_24.setObjectName("mc_24")
        self.gridLayout.addWidget(self.mc_24, 4, 10, 1, 1)
        self.bh_27 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_27.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_27.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_27.setReadOnly(True)
        self.bh_27.setObjectName("bh_27")
        self.gridLayout.addWidget(self.bh_27, 7, 9, 1, 1)
        self.bh_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bh_11.setMinimumSize(QtCore.QSize(130, 30))
        self.bh_11.setMaximumSize(QtCore.QSize(130, 16777215))
        self.bh_11.setReadOnly(True)
        self.bh_11.setObjectName("bh_11")
        self.gridLayout.addWidget(self.bh_11, 1, 5, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 1011, 54))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(50, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.serial_port = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.serial_port.setMaximumSize(QtCore.QSize(60, 16777215))
        self.serial_port.setObjectName("serial_port")
        self.horizontalLayout_2.addWidget(self.serial_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 20))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.baud_rate = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.baud_rate.setMaximumSize(QtCore.QSize(60, 16777215))
        self.baud_rate.setObjectName("baud_rate")
        self.horizontalLayout_3.addWidget(self.baud_rate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 100, 100, 40))
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.passNumber = QtWidgets.QLineEdit(Form)
        self.passNumber.setGeometry(QtCore.QRect(260, 100, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.passNumber.setFont(font)
        self.passNumber.setText("")
        self.passNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.passNumber.setObjectName("passNumber")
        self.max_device = QtWidgets.QLineEdit(Form)
        self.max_device.setGeometry(QtCore.QRect(620, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.max_device.setFont(font)
        self.max_device.setAlignment(QtCore.Qt.AlignCenter)
        self.max_device.setObjectName("max_device")
        self.max_device_title = QtWidgets.QLabel(Form)
        self.max_device_title.setGeometry(QtCore.QRect(500, 100, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.max_device_title.setFont(font)
        self.max_device_title.setObjectName("max_device_title")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.bhList = [self.bh_1,self.bh_2,self.bh_3,self.bh_4,self.bh_5,self.bh_6,self.bh_7,self.bh_8,self.bh_9,self.bh_10,
                       self.bh_11,self.bh_12,self.bh_13,self.bh_14,self.bh_15,self.bh_16,self.bh_17,self.bh_18,self.bh_19,self.bh_20,
                       self.bh_21,self.bh_22,self.bh_23,self.bh_24,self.bh_25,self.bh_26,self.bh_27,self.bh_28,self.bh_29,self.bh_30]
        self.mcList = [self.mc_1,self.mc_2,self.mc_3,self.mc_4,self.mc_5,self.mc_6,self.mc_7,self.mc_8,self.mc_9,self.mc_10,
                       self.mc_11,self.mc_12,self.mc_13,self.mc_14,self.mc_15,self.mc_16,self.mc_17,self.mc_18,self.mc_19,self.mc_20,
                       self.mc_21,self.mc_22,self.mc_23,self.mc_24,self.mc_25,self.mc_26,self.mc_27,self.mc_28,self.mc_29,self.mc_30]
        self.cjList = [self.cj_1,self.cj_2,self.cj_3,self.cj_4,self.cj_5,self.cj_6,self.cj_7,self.cj_8,self.cj_9,self.cj_10,
                       self.cj_11,self.cj_12,self.cj_13,self.cj_14,self.cj_15,self.cj_16,self.cj_17,self.cj_18,self.cj_19,self.cj_20,
                       self.cj_21,self.cj_22,self.cj_23,self.cj_24,self.cj_25,self.cj_26,self.cj_27,self.cj_28,self.cj_29,self.cj_30]
        self.userIds = ['','','','','','','','','','','','','','','','','','','','','','','','','','','','','','']

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sb_21.setText(_translate("Form", "设备21："))
        self.sb_title_2.setText(_translate("Form", "设备"))
        self.sb_23.setText(_translate("Form", "设备23："))
        self.cj_title_3.setText(_translate("Form", "成绩"))
        self.cj_title_2.setText(_translate("Form", "成绩"))
        self.sb_title_3.setText(_translate("Form", "设备"))
        self.mc_title_3.setText(_translate("Form", "姓名"))
        self.bh_title_3.setText(_translate("Form", "人员编号"))
        self.sb_title_1.setText(_translate("Form", "设备"))
        self.bh_title_1.setText(_translate("Form", "人员编号"))
        self.cj_title_1.setText(_translate("Form", "成绩"))
        self.mc_title_1.setText(_translate("Form", "姓名"))
        self.mc_title_2.setText(_translate("Form", "姓名"))
        self.sb_4.setText(_translate("Form", "设备4："))
        self.sb_1.setText(_translate("Form", "设备1："))
        self.sb_2.setText(_translate("Form", "设备2："))
        self.sb_3.setText(_translate("Form", "设备3："))
        self.sb_5.setText(_translate("Form", "设备5："))
        self.sb_6.setText(_translate("Form", "设备6："))
        self.sb_7.setText(_translate("Form", "设备7："))
        self.sb_30.setText(_translate("Form", "设备30："))
        self.sb_24.setText(_translate("Form", "设备24："))
        self.sb_14.setText(_translate("Form", "设备14："))
        self.sb_10.setText(_translate("Form", "设备10："))
        self.sb_27.setText(_translate("Form", "设备27："))
        self.sb_9.setText(_translate("Form", "设备9："))
        self.sb_8.setText(_translate("Form", "设备8："))
        self.sb_29.setText(_translate("Form", "设备29："))
        self.bh_title_2.setText(_translate("Form", "人员编号"))
        self.sb_19.setText(_translate("Form", "设备19："))
        self.sb_28.setText(_translate("Form", "设备28："))
        self.sb_22.setText(_translate("Form", "设备22："))
        self.sb_25.setText(_translate("Form", "设备25："))
        self.sb_11.setText(_translate("Form", "设备11："))
        self.sb_17.setText(_translate("Form", "设备17："))
        self.sb_13.setText(_translate("Form", "设备13："))
        self.sb_16.setText(_translate("Form", "设备16："))
        self.sb_26.setText(_translate("Form", "设备26："))
        self.sb_12.setText(_translate("Form", "设备12："))
        self.sb_20.setText(_translate("Form", "设备20："))
        self.sb_18.setText(_translate("Form", "设备18："))
        self.sb_15.setText(_translate("Form", "设备15："))
        self.label.setText(_translate("Form", "仰卧起坐测试"))
        self.label_2.setText(_translate("Form", "串  口："))
        self.label_3.setText(_translate("Form", "波特率："))
        self.pushButton.setText(_translate("Form", "开始检录"))
        self.pushButton_6.setText(_translate("Form", "停止检录"))
        self.pushButton_5.setText(_translate("Form", "下一个"))
        self.pushButton_2.setText(_translate("Form", "开始接收数据"))
        self.pushButton_3.setText(_translate("Form", "停止接收数据"))
        self.pushButton_4.setText(_translate("Form", "清零"))
        self.pushButton_7.setText(_translate("Form", "过号"))
        self.max_device.setText(_translate("Form", "0"))
        self.max_device_title.setText(_translate("Form", "可用设备数："))

        self.pushButton.clicked.connect(self.runReadCard)
        self.pushButton_6.clicked.connect(self.stopReadCard)
        self.pushButton_2.clicked.connect(self.startRun)
        self.pushButton_3.clicked.connect(self.stopData)
        self.pushButton_4.clicked.connect(self.clearText)
        self.pushButton_5.clicked.connect(self.nextPerson)
        self.pushButton_7.clicked.connect(self.passPersion)

        self.showMsgSignal.connect(self.showMsg)

    # def readPerson(self):
    #     if(self.allPerson>=30):
    #         qw = QtWidgets.QWidget()
    #         QMessageBox.warning(qw,'警告','单次最多检录30人', QMessageBox.Ok)
    #     else:
    #         self.writeInfo()

    def runReadCard(self):
        self.lastCardId = ''
        _thread.start_new_thread(self.readCard,())

    def readCard(self):
        self.readCardFlag = True
        self.pushButton.setEnabled(False)
        self.pushButton.setText("正在检录")
        while self.readCardFlag:
            cardId = utils.readCardUtils.getCardId(self.lastCardId)
            if cardId!='':
                self.lastCardId = cardId
                _thread.start_new_thread( self.writeInfo, (cardId, ) )

    #停止检录
    def stopReadCard(self):
        self.readCardFlag = False
        self.pushButton.setEnabled(True)
        self.pushButton.setText("开始检录")

    #显示对话框
    def showMsg(self,msg):
        qw = QtWidgets.QWidget()
        QMessageBox.warning(qw,'消息',msg)

    #刷卡检录
    def writeInfo(self,cardId):
        # cardId = utils.readCardUtils.getCardId()
        # if cardId=='':
        #     qw = QtWidgets.QWidget()
        #     QMessageBox.warning(qw,'警告','请先放卡再点击检录', QMessageBox.Ok)
        #     return
        results = self.stat.fetchall("select * from user_info where card_number=%s"%cardId)
        # print(results)
        if results==():
            # qw = QtWidgets.QWidget()
            # QMessageBox.warning(qw,'警告','非本系统卡', QMessageBox.Ok)
            self.showMsgSignal.emit("非本系统卡")
        else:
            sql = "INSERT INTO sit_ups_check(id,job_number,name,user_id,create_time) VALUES('%s','%s','%s','%s','%s')"%(uuid.uuid1(),results[0][4],results[0][1],results[0][0],time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
            if self.stat.insert(sql)>0:
                # qw = QtWidgets.QWidget()
                # QMessageBox.warning(qw,'消息',results[0][1]+" "+results[0][4]+" 检录成功", QMessageBox.Ok)
                self.showMsgSignal.emit(results[0][1]+" "+results[0][4]+" 检录成功")
            else:
                # qw = QtWidgets.QWidget()
                # QMessageBox.warning(qw,'错误',"检录失败", QMessageBox.Ok)
                self.showMsgSignal.emit("检录失败")
            # bh.setText(results[0][4])
            # mc.setText(results[0][1])
            # self.userIds.append(results[0][0])
            # self.nowPerson+=1
            # self.allPerson+=1

    def nextPerson(self):
        if self.allPerson>=int(self.max_device.text()):
            qw = QtWidgets.QWidget()
            QMessageBox.warning(qw,'警告','单次最多检录'+self.max_device.text()+'人', QMessageBox.Ok)
            return
        sql = "SELECT id,job_number,name,user_id FROM sit_ups_check ORDER BY create_time LIMIT 1"
        results = self.stat.fetchall(sql)
        if results==():
            qw = QtWidgets.QWidget()
            QMessageBox.warning(qw,'警告','无检录人员', QMessageBox.Ok)
            return
        for index,userId in enumerate(self.userIds):
            if(self.userIds[index]==""):
                self.userIds[index] = results[0][3]
                self.bhList[index].setText(results[0][1]) 
                self.mcList[index].setText(results[0][2])
                self.allPerson+=1
                break
        sql = "DELETE FROM sit_ups_check WHERE id='%s'"%results[0][0]
        self.stat.delete(sql)

    def startRun(self):
        if self.serial_port.text()=='' or self.baud_rate.text()=='':
            qw = QtWidgets.QWidget()
            QMessageBox.warning(qw,'警告',"串口号和波特率不能为空", QMessageBox.Ok)
            return
        try:
            x = serial.Serial(self.serial_port.text(), self.baud_rate.text())
            self.dataFlag = True
            self.pushButton_3.setEnabled(True)
            _thread.start_new_thread( self.getData, (x, ) )
            # t = Thread(target=self.getData,(x))
            # t.start()
        except:
            qw = QtWidgets.QWidget()
            QMessageBox.warning(qw,'错误',"连接串口失败，请检查串口号和波特率是否正确", QMessageBox.Ok)


    def getData(self,x):
        self.pushButton_2.setText('接收数据中')
        self.pushButton_2.setEnabled(False)
        myout = []
        index = 0
        while self.dataFlag:
            while x.inWaiting() > 0:
                myout.append(x.read(1))
            if myout != []:
                # myout = [b'\xAA', b'\x02', b'\x00', b'\x01', b'\xD0', b'\xD1', b'\xD2', b'\x01']
                print(myout)
                if self.bhList[int(myout[1].hex(),16)-2].text()=="":
                    continue
                self.cjList[int(myout[1].hex(),16)-2].setText(str(int(myout[6].hex(),16)))
                print(int(myout[1].hex(),16)-2)
                self.uploadGrade(int(myout[1].hex(),16)-2)
                myout = []
        self.allPerson-=1
        self.pushButton_2.setText('开始接收数据')
        self.pushButton_2.setEnabled(True)
        # res = [b'\xAA', b'\xFB', b'\x00', b'\x01', b'\xD0', b'\xD1', b'\xD2', b'\xD3']
        # print(int(res[1].hex(),16))
        # print(int(res[7].hex(),16))

    def stopData(self):
        self.dataFlag = False

    #上传成绩
    def uploadGrade(self,uploadNo):
        sql = "INSERT INTO sit_ups_result(id,grade,user_id,create_time) VALUES('%s','%s','%s','%s')"%(uuid.uuid1(),self.cjList[uploadNo].text(),self.userIds[uploadNo],time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
        # print(sql)
        if self.stat.insert(sql)<=0:
            qw = QtWidgets.QWidget()
            QMessageBox.warning(qw,'消息',"设备"+(int(self.cjList[uploadNo])+1)+"上传失败", QMessageBox.Ok)
        self.bhList[uploadNo].setText("")
        self.mcList[uploadNo].setText("")
        self.cjList[uploadNo].setText("")
        self.userIds[uploadNo]=""
    
    #过号
    def passPersion(self):
        if(self.passNumber.text()==''):
            self.showMsgSignal.emit("该设备无测试人员")
            return
        passNum = int(self.passNumber.text())
        if(passNum<1 or passNum>30):
            self.showMsgSignal.emit("请输入1-30的设备号")
        else:
            self.bhList[passNum-1].setText("")
            self.mcList[passNum-1].setText("")
            self.cjList[passNum-1].setText("")
            self.userIds[passNum-1]=""
            self.allPerson-=1

    #清理数据
    def clearText(self):
        for i in range(30):
            self.bhList[i].setText('')
            self.mcList[i].setText('')
            self.cjList[i].setText('')
            self.userIds[i] = ''
            self.nowPerson=0
            self.allPerson=0